# Generated by Django 5.2.8 on 2025-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA')], max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
