# Generated by Django 5.2.8 on 2025-11-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CERTIFICATION', 'Certification'), ('SKILL', 'Skill'), ('CGPA', 'CGPA'), ('OTHER', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('value', models.CharField(blank=True, max_length=64)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', '-created_at'],
            },
        ),
    ]
