# Generated by Django 5.2.8 on 2025-11-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('CERTIFICATION', 'Certification'), ('SKILL', 'Skill'), ('CGPA', 'CGPA'), ('BADGE', 'Badge'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
