# Generated by Django 5.2.8 on 2025-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_achievement_earned_on_achievement_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
